version: '3.9'

services:
  db:
    image: postgres
    container_name: tracklab_db
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks:
      - db_network
  minio:
    image: minio/minio
    container_name: minio
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # Web UI
    command: server /data --console-address ":9001"
    volumes:
      - ./minio_data:/data

networks:
  db_network:
    driver: bridge
