onlyBuiltDependencies:
  - '@nestjs/core'
  - '@parcel/watcher'
  - '@prisma/client'
  - '@prisma/engines'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - bcrypt
  - esbuild
  - lmdb
  - msgpackr-extract
  - nx
  - prisma
  - protobufjs
  - protoc
  - unrs-resolver
