[project]
name = "nx-workspace"
version = "1.0.0"
dependencies = [
 "fast-f1-service",
 "grpcio>=1.71.0",
 "grpcio-tools>=1.71.0",
]

[tool.uv.workspace]
members = [ "apps/fast-f1-service" ]

[tool.uv.sources.fast-f1-service]
workspace = true

[dependency-groups]
dev = [ ]
